### PR TITLE
Update of file headers, etc.

### PR DESCRIPTION
**Pull request by vaclavkratochvil**

### CODE REVIEW

**Comment by vaclavkratochvil** [comment]
I recompile the files. I am still missing one.

**Comment by vaclavkratochvil** [comment]
Now, it is ready to merge.

V.

**Comment by vaclavkratochvil** [comment]
I noticed wrong length of the respective files - fixed

**Comment by vaclavkratochvil** [comment]
just design

**Review by lawrennd — APPROVED** [review]
Changes to binary files from publication editor or correction to headers.

**Comment by lawrennd** [comment]
Thanks Vaclav!

**Pull request merged**
